var number = -5;
var absoluteNumber = Math.abs(number);
console.log(absoluteNumber);
var number = 5.953535;
var result = Math.round(number);
console.log(result);
var number = 5.953535;
var result = Math.ceil(number);
console.log(result);
var number = 5.953535;
var result = Math.floor(number);
console.log(result);
var number = 5.953535;
var result = Math.random();
console.log(result);
var number = Math.random()*100;
var result = Math.round(number);
console.log(result);
